### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by dehli** [dehli/techstarter#1]

**Comment by tkruml** [comment]
![deathtostock_wired10](https://cloud.githubusercontent.com/assets/7574500/7058594/2debbbfc-de32-11e4-830d-e8e48b113c7f.jpg)
![deathtostock_wired9](https://cloud.githubusercontent.com/assets/7574500/7058595/2debcc6e-de32-11e4-96ba-3a5aae1fef42.jpg)
![ganqcr1brtu-william-iven](https://cloud.githubusercontent.com/assets/7574500/7058610/6b262a02-de32-11e4-97b3-ad29cb5a3d58.jpg)
![public-domain-images-free-stock-photos-high-quality-resolution-downloads-public-domain-archive-14](https://cloud.githubusercontent.com/assets/7574500/7058644/dda95a90-de32-11e4-84c8-06b4cc44098e.jpg)

**Comment by tkruml** [comment]
![img_1123](https://cloud.githubusercontent.com/assets/7574500/7058710/94f7f440-de33-11e4-82e2-0de0cde65902.jpg)
![img_0574](https://cloud.githubusercontent.com/assets/7574500/7058716/a6a180da-de33-11e4-9d98-61fcd4b12d52.jpg)
![img_0899](https://cloud.githubusercontent.com/assets/7574500/7058719/a6a378fe-de33-11e4-81b0-26690a841c61.jpg)
![img_0897](https://cloud.githubusercontent.com/assets/7574500/7058715/a69fbc5a-de33-11e4-9632-513f52305bb9.jpg)
![img_0896](https://cloud.githubusercontent.com/assets/7574500/7058718/a6a33c5e-de33-11e4-8f77-274ef5ff9767.jpg)
![img_1120](https://cloud.githubusercontent.com/assets/7574500/7058717/a6a1aed4-de33-11e4-88c4-f8b8478bb1e3.jpg)
![img_1119](https://cloud.githubusercontent.com/assets/7574500/7058723/a6f77e86-de33-11e4-9620-a14463cfa5d8.jpg)
![img_1118](https://cloud.githubusercontent.com/assets/7574500/7058720/a6aa1f6a-de33-11e4-92bd-f4e20ec5c9d5.jpg)
![img_1117](https://cloud.githubusercontent.com/assets/7574500/7058721/a6aa4670-de33-11e4-9945-5f88a8923c55.jpg)
![img_1116](https://cloud.githubusercontent.com/assets/7574500/7058722/a6ac754e-de33-11e4-971a-31f79a564cc5.jpg)

**Comment by tkruml** [comment]
![img_1125](https://cloud.githubusercontent.com/assets/7574500/7058736/ccde5372-de33-11e4-9f76-2eba9b6dad8f.jpg)

**Comment by tkruml** [comment]
Home page
![simple resources and steps to learn](https://cloud.githubusercontent.com/assets/7574500/7059269/17101efa-de3c-11e4-9eab-61e34035b86e.png)

**Comment by tkruml** [comment]
the one without a spelling error
![simple resources and steps to learn 1](https://cloud.githubusercontent.com/assets/7574500/7059298/c39c164c-de3c-11e4-81ef-c4fea7dbe407.png)
